/**
 * ⭐ SINGLE SOURCE OF CONTENT — everything the site displays lives here.
 * How to edit safely: see docs/CONTENT.md. To add a project, use the
 * /add-project skill (or follow .claude/skills/add-project/SKILL.md manually).
 *
 * Media paths are relative to public/ WITHOUT a leading slash
 * (e.g. 'projects/jitsuites/cover.svg') so they work under the GitHub Pages
 * basePath. Placeholder covers are generated by `npm run placeholders`.
 */

export type ProjectMedia = {
  /** 16:9 cover, 1600×900. Placeholder .svg until a real .webp/.jpg replaces it. */
  cover: string
  /** Optional extra stills: 'projects/<slug>/gallery-1.webp', ... */
  gallery?: string[]
  /** Optional short muted loop: 'projects/<slug>/loop.mp4' (≤8s, ≤3MB). */
  video?: string
}

export const PERSONAL = {
  name: 'Muhammad Muqeet Khan',
  initials: 'MK',
  role: 'MERN Stack Developer',
  location: 'Islamabad, Pakistan',
  email: 'muqeetkhan010@gmail.com',
  phone: '+92 333 5248912',
  github: 'https://github.com/muqeetkhann',
  linkedin: 'https://linkedin.com/in/muqeet-khan',
  portfolio: '#',
  bio: 'Full-stack MERN developer building fast, scalable web apps end-to-end — React & Next.js frontends backed by Node.js / Express APIs and MongoDB. 2 years shipping production software across SaaS platforms, e-commerce marketplaces, and Web3 DeFi apps.',
}

export const EXPERIENCE = [
  {
    role: 'MERN Stack Developer',
    company: 'Fexen Smart Solutions',
    period: 'Sep 2024 – Present',
    location: 'Islamabad, Pakistan',
    accent: '#6EE7B7',
    bullets: [
      'Delivered full-stack features end-to-end on 10+ client projects — from React/Next.js frontends to Node.js/Express APIs and MongoDB data layers.',
      'Built REST APIs with Node.js and Express, Mongoose data models, JWT authentication, and role-based access control.',
      'Engineered advanced features: drag-and-drop page builders, real-time WebSocket dashboards, and multi-tenant SaaS flows.',
      'Developed and maintained component libraries of 30–80+ components using Radix UI, Tailwind CSS, and shadcn/ui.',
      'Integrated third-party services including Stripe, Firebase, Google OAuth, Brevo, and Web3 wallet providers.',
    ],
  },
  {
    role: 'Frontend Developer Intern',
    company: 'Stack One Technologies',
    period: 'June 2024 – August 2024',
    location: 'Islamabad, Pakistan',
    accent: '#93C5FD',
    bullets: [
      'Built responsive UIs with React.js, Tailwind CSS, and Bootstrap; optimised performance via lazy loading and code splitting.',
      'Implemented form validation, dynamic rendering, and React Router for SPA experiences.',
      'Practised Git-based version control and feature branching in an agile team environment.',
    ],
  },
]

/** A single project entry. */
export type Project = {
  id: number
  title: string
  type: string
  url: string
  urlLabel: string
  cat: string
  accent: string
  num: string
  slug: string
  media: ProjectMedia
  desc: string
  highlights: string[]
  tags: string[]
}

const CLIENT_PROJECTS: Project[] = [
  {
    id: 1,
    title: 'JitSuites',
    type: 'SaaS Platform',
    url: 'https://jitsuites.com',
    urlLabel: 'jitsuites.com',
    cat: 'saas',
    accent: '#6EE7B7',
    num: '01',
    slug: 'jitsuites',
    media: { cover: 'projects/jitsuites/cover.svg' },
    desc: 'Multi-channel marketing automation platform — funnel builder, email/SMS marketing, social media auto-posting, and video marketing from a single dashboard.',
    highlights: [
      'Architected drag-and-drop funnel/landing page builder using @dnd-kit with element tree manipulation, undo/redo history, layer management, and JSON/HTML export.',
      'Built visual email builder with React Email Editor, merge tag validation, and multi-platform scheduling via React Big Calendar.',
      'Developed 30+ reusable UI components; data tables with server-side pagination, sorting, filtering, and URL state persistence via TanStack Table.',
    ],
    tags: ['React 19', 'TanStack Router', 'TanStack Query', 'Zustand', '@dnd-kit', 'Radix UI', 'Brevo API'],
  },
  {
    id: 2,
    title: 'Kompra',
    type: 'E-Commerce Marketplace',
    url: 'https://dropex-marketplace.pages.dev',
    urlLabel: 'dropex-marketplace.pages.dev',
    cat: 'ecom',
    accent: '#93C5FD',
    num: '02',
    slug: 'kompra',
    media: { cover: 'projects/kompra/cover.svg' },
    desc: 'Full-featured multi-sided marketplace with a public storefront, seller dashboard, and role-based admin panel for order managers, staff, and procurement managers.',
    highlights: [
      'Architected three distinct interfaces — public storefront, seller dashboard with granular RBAC (order/staff/procurement managers), and admin panel.',
      'Implemented dynamic category-based recommendations via recursive tree traversal and multi-step checkout with optimistic UI updates.',
      'Integrated OTP authentication flow, i18next English/Spanish localization, and persistent cart state via Zustand.',
    ],
    tags: ['React 18', 'TanStack Router', 'TanStack Query', 'Zustand', 'TypeScript', 'Radix UI', 'i18next'],
  },
  {
    id: 3,
    title: 'Kompra Seller portal',
    type: 'B2B SaaS / Logistics',
    url: 'https://dropi-clone.pages.dev',
    urlLabel: 'dropi-clone.pages.dev',
    cat: 'saas',
    accent: '#FDE68A',
    num: '03',
    slug: 'kompra-seller',
    media: { cover: 'projects/kompra-seller/cover.svg' },
    desc: 'B2B dropshipping and logistics SaaS for Latin American sellers — manages products, orders, warehouses, and earnings with role-based access control.',
    highlights: [
      'Implemented RBAC with three user types using TanStack Router beforeLoad hooks, dynamic sidebar filtering, and token-based redirects.',
      'Built centralized API client with JWT injection, automatic refresh token storage, and content-type negotiation for JSON/FormData/CSV.',
      'Delivered 80+ reusable components, 15+ API service modules, Vitest unit tests, and full TypeScript coverage.',
    ],
    tags: ['React 18', 'TanStack Table', 'Recharts', 'Zod', 'React Hook Form', 'i18next', 'Vitest'],
  },
  {
    id: 4,
    title: 'Extsy',
    type: 'Crypto Trading Platform',
    url: 'https://extsy.com',
    urlLabel: 'extsy.com',
    cat: 'web3',
    accent: '#C4B5FD',
    num: '04',
    slug: 'extsy',
    media: { cover: 'projects/extsy/cover.svg' },
    desc: 'Full-featured crypto trading platform with P2P trading, staking, virtual cards, and Web3 wallet integrations. Built as part of a 10–15 person team.',
    highlights: [
      'Integrated TronWeb and Wagmi for Web3 wallet connections; Stripe payments and Firebase authentication.',
      'Built complex modal systems (staking, KYC, payment flows), real-time data tables, and role-based route protection.',
      'Implemented dark/light theme with persistent state; Framer Motion and Lottie animations throughout.',
    ],
    tags: ['Next.js 14', 'Redux Toolkit', 'Chakra UI', 'Wagmi', 'TronWeb', 'Framer Motion', 'Stripe'],
  },
  {
    id: 5,
    title: 'ASAP Pay',
    type: 'Fintech SaaS Dashboard',
    url: 'https://asap-stg.pages.dev',
    urlLabel: 'asap-stg.pages.dev',
    cat: 'web3',
    accent: '#FCA5A5',
    num: '05',
    slug: 'asap-pay',
    media: { cover: 'projects/asap-pay/cover.svg' },
    desc: 'Fintech SaaS enabling crypto/fiat wallet management, P2P trading, currency swapping, virtual card issuance, bill payments, and AI-powered financial assistance.',
    highlights: [
      'Built 40+ routes with responsive layouts, Framer Motion animations, and Ant Design components.',
      'Developed P2P trading interfaces with trade modals, payment status indicators, countdown timers, and virtual card management.',
      'Implemented complete auth UI — login, signup, OTP verification, and 2FA setup using React Hook Form.',
    ],
    tags: ['React 18', 'TypeScript', 'Ant Design', 'TanStack Query', 'Framer Motion', 'i18n'],
  },
  {
    id: 6,
    title: 'Ethoro',
    type: 'Web3 / DeFi',
    url: 'https://dev.ethoro.io',
    urlLabel: 'dev.ethoro.io',
    cat: 'web3',
    accent: '#6EE7B7',
    num: '06',
    slug: 'ethoro',
    media: { cover: 'projects/ethoro/cover.svg' },
    desc: 'Crypto staking platform for ERC-20 tokens with Web3 wallet integration and admin dashboard for managing tokens, subscriptions, and withdrawals.',
    highlights: [
      'Engineered Web3 deposit flow with ERC20 approval, smart contract interaction, token decimals conversion, and multi-step wallet confirmations.',
      'Architected JWT-based protected routes with TanStack Router beforeLoad hooks, automatic token refresh, and role-based redirects.',
      'Built admin layer with Chart.js analytics, CSV data exports, and referral/withdrawal management.',
    ],
    tags: ['React 19', 'Wagmi / viem', 'Reown AppKit', 'TanStack Query', 'Tailwind CSS v4', 'Sepolia'],
  },
  {
    id: 7,
    title: 'Katana Healthcare',
    type: 'Marketing Website',
    url: 'https://katana-healthcare.com',
    urlLabel: 'katana-healthcare.com',
    cat: 'site',
    accent: '#93C5FD',
    num: '07',
    slug: 'katana-healthcare',
    media: { cover: 'projects/katana-healthcare/cover.svg' },
    desc: 'SaaS marketing site for a clinical decision support platform targeting healthcare professionals with BNF-based prescribing tools.',
    highlights: [
      'Engineered synchronized dual-vertical Swiper carousel with real-time center image updates and bidirectional slide sync.',
      'Implemented scroll-aware sticky header with directional visibility detection (hide on scroll-down, reveal on scroll-up).',
      'Deployed to Vercel with HubSpot forms, Google Analytics, and Microsoft Clarity integration.',
    ],
    tags: ['Next.js 16', 'React 19', 'Tailwind CSS 4', 'Swiper 12', 'HubSpot'],
  },
  {
    id: 8,
    title: 'ZawayaDAO',
    type: 'Web3 Marketing Site',
    url: 'https://zawayadao.com',
    urlLabel: 'zawayadao.com',
    cat: 'site web3',
    accent: '#C4B5FD',
    num: '08',
    slug: 'zawayadao',
    media: {
      cover: 'projects/zawayadao/cover.webp',
      gallery: ['projects/zawayadao/gallery-1.webp', 'projects/zawayadao/gallery-2.webp', 'projects/zawayadao/gallery-3.webp'],
    },
    desc: 'White-label SaaS for real estate tokenization with DAO-ready RWA infrastructure and a custom WebGL interactive background.',
    highlights: [
      'Engineered PixelBlast component with custom GLSL fragment shaders — FBM noise, liquid ripple effects, and pointer tracking.',
      'Implemented IntersectionObserver scroll animations, JSON-LD structured data, and SEO-optimized metadata.',
    ],
    tags: ['Next.js 16', 'Three.js', 'GLSL Shaders', 'TypeScript', 'Tailwind CSS 4'],
  },
  {
    id: 9,
    title: 'Travaleo',
    type: 'Real Estate Platform',
    url: 'https://travaleo.com',
    urlLabel: 'travaleo.com',
    cat: 'site',
    accent: '#FDE68A',
    num: '09',
    slug: 'travaleo',
    media: { cover: 'projects/travaleo/cover.svg' },
    desc: 'Tokenized real estate investment platform enabling fractional ownership of luxury properties for high-net-worth investors.',
    highlights: [
      'Integrated dual CMS APIs (Strapi + custom REST) with unified TypeScript interfaces and React Query caching.',
      'Built TokenCard components with Swiper galleries, dynamic ROI calculations, and funding progress bars.',
      'Full SEO stack: Schema.org structured data, Open Graph tags, Google Analytics, and server-side rendering.',
    ],
    tags: ['Next.js 15', 'Strapi CMS', 'TanStack Query', 'Radix UI', 'shadcn/ui', 'Swiper'],
  },
  {
    id: 10,
    title: 'Singularity',
    type: 'Web3 / DeFi',
    url: 'https://singularity-web-app-lime.vercel.app',
    urlLabel: 'singularity-web-app-lime.vercel.app',
    cat: 'web3',
    accent: '#6EE7B7',
    num: '10',
    slug: 'singularity',
    media: {
      cover: 'projects/singularity/cover.webp',
      gallery: ['projects/singularity/gallery-1.webp', 'projects/singularity/gallery-2.webp', 'projects/singularity/gallery-3.webp'],
    },
    desc: 'DeFi yield farming platform with Ethereum wallet connectivity, smart contract interaction, and real-time on-chain metrics dashboard.',
    highlights: [
      'Implemented Ethereum wallet connectivity using Reown AppKit with wagmi/viem, supporting mainnet and Sepolia with automatic chain switching.',
      'Built async data hooks using viem contract read functions integrated with React Query for real-time on-chain state.',
      'Created protected routes validating wallet connection status with multi-chain header support.',
    ],
    tags: ['Next.js 16', 'Wagmi / viem', 'Reown AppKit', 'TanStack Query', 'Tailwind CSS 4', 'DeFi'],
  },
  {
    id: 11,
    title: 'Blockyfy',
    type: 'Agency Website',
    url: '',
    urlLabel: '',
    cat: 'site',
    accent: '#6EE7B7',
    num: '11',
    slug: 'blockyfy',
    media: {
      cover: 'projects/blockyfy/cover.webp',
      gallery: ['projects/blockyfy/gallery-1.webp', 'projects/blockyfy/gallery-2.webp'],
    },
    desc: 'Agency site with custom country code selector (50+ countries), Cal.com scheduling, and WhatsApp chat.',
    highlights: [],
    tags: ['React', 'Tailwind', 'Cal.com'],
  },
  {
    id: 12,
    title: 'NextSense',
    type: 'Tech Website',
    url: '',
    urlLabel: '',
    cat: 'site',
    accent: '#93C5FD',
    num: '12',
    slug: 'nextsense',
    media: {
      cover: 'projects/nextsense/cover.webp',
      gallery: ['projects/nextsense/gallery-1.webp', 'projects/nextsense/gallery-2.webp', 'projects/nextsense/gallery-3.webp'],
    },
    desc: 'Web3/AI tech site with complex multi-level dropdown nav and dynamic dark/light mode per page.',
    highlights: [],
    tags: ['Next.js', 'Tailwind', 'Dark Mode'],
  },
  {
    id: 13,
    title: 'Regen Digital',
    type: 'RWA Tokenization',
    url: '',
    urlLabel: '',
    cat: 'site',
    accent: '#C4B5FD',
    num: '13',
    slug: 'regen-digital',
    media: { cover: 'projects/regen-digital/cover.svg' },
    desc: 'Real estate tokenization site with 8+ pages and reusable component system utilizing class-variance-authority for tight UI scaling.',
    highlights: [],
    tags: ['Next.js', 'CVA', 'Tailwind'],
  },
]

const FEATURED_MERN: Project[] = [
  {
    id: 14,
    title: 'Inglés Academics',
    type: 'Full-Stack LMS Platform',
    url: '',
    urlLabel: '',
    cat: 'saas',
    accent: '#6EE7B7',
    num: '14',
    slug: 'ingles-academics',
    media: {
      cover: 'projects/ingles-academics/cover.webp',
      gallery: ['projects/ingles-academics/gallery-1.webp', 'projects/ingles-academics/gallery-2.webp', 'projects/ingles-academics/gallery-3.webp'],
    },
    desc: 'Class-management and analytics platform for an online English academy — weekly scheduling, attendance, student progress, live classes, and role-based staff access.',
    highlights: [
      'Built a full-stack MERN platform managing 480+ classes and 200+ students with weekly scheduling, attendance tracking, and live-class management.',
      'Engineered an analytics dashboard (attendance over time, classes by level and time of day) powered by MongoDB aggregation pipelines.',
      'Implemented role-based access control across teachers, students, and admins with JWT authentication and protected routes.',
    ],
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Recharts', 'JWT'],
  },
  {
    id: 15,
    title: 'Inglés CRM',
    type: 'Full-Stack Sales CRM',
    url: '',
    urlLabel: '',
    cat: 'saas',
    accent: '#93C5FD',
    num: '15',
    slug: 'ingles-crm',
    media: {
      cover: 'projects/ingles-crm/cover.webp',
      gallery: ['projects/ingles-crm/gallery-1.webp', 'projects/ingles-crm/gallery-2.webp', 'projects/ingles-crm/gallery-3.webp'],
    },
    desc: 'Sales CRM for a language-education business — lead pipelines, setter/closer workflows, show-up and recovery funnels, revenue goals, and commission tracking.',
    highlights: [
      'Developed a MERN sales CRM with lead management, booking/call scheduling, and setter/closer assignment across a multi-stage funnel.',
      'Built real-time funnel analytics — confirmation, show-up, conversion, and recovery rates — plus revenue-goal and commission dashboards.',
      'Integrated UTM attribution and opt-in tracking to measure top-of-funnel performance by channel.',
    ],
    tags: ['React', 'Node.js', 'Express', 'MongoDB', 'Chart.js', 'REST APIs'],
  },
]

/**
 * Display order: featured MERN work first, then client work.
 * `num` badges are derived from position — never hand-edit them.
 */
export const PROJECTS: Project[] = [...FEATURED_MERN, ...CLIENT_PROJECTS].map(
  (project, index) => ({ ...project, num: String(index + 1).padStart(2, '0') }),
)

/**
 * Hero spotlight rotation — the featured cards that cycle in the intro.
 * Derived from the projects that ship a real cover image (`.webp`), keeping
 * the hero visual instead of showing generated placeholders. Order follows
 * PROJECTS (featured MERN work first).
 */
export const SPOTLIGHT: Project[] = PROJECTS.filter(p => p.media.cover.endsWith('.webp')).slice(0, 5)

/** Domains worked across — short editorial tagline in the hero. */
export const HERO_DOMAINS = ['SaaS', 'Web3', 'E-Commerce', 'Fintech']

export const SKILLS = [
  { cat: 'Languages', items: ['JavaScript (ES6+)', 'TypeScript', 'HTML5', 'CSS3', 'GLSL'] },
  { cat: 'Frontend', items: ['React 18/19', 'Next.js (App Router)', 'TanStack Query/Router', 'Redux Toolkit', 'Zustand'] },
  { cat: 'Backend', items: ['Node.js', 'Express.js', 'REST APIs', 'JWT / Auth', 'WebSockets'] },
  { cat: 'Databases', items: ['MongoDB', 'Mongoose', 'Firebase', 'PostgreSQL'] },
  { cat: 'Styling', items: ['Tailwind CSS', 'Radix UI', 'shadcn/ui', 'Framer Motion', 'Chakra UI'] },
  { cat: 'Web3', items: ['Wagmi / viem', 'Reown AppKit', 'TronWeb', 'ERC-20', 'Three.js'] },
  { cat: 'Integrations', items: ['Stripe', 'Google OAuth', 'Brevo', 'HubSpot', 'Cloudinary'] },
  { cat: 'Tooling', items: ['Git / GitHub', 'Vercel', 'Vite', 'Vitest', 'ESLint / Prettier'] },
]

export const FILTERS = [
  { label: 'All', value: 'all' },
  { label: 'SaaS / Platforms', value: 'saas' },
  { label: 'Web3 / Crypto', value: 'web3' },
  { label: 'E-Commerce', value: 'ecom' },
  { label: 'Marketing Sites', value: 'site' },
]
