export const PERSONAL = {
  name: 'Muhammad Muqeet Khan',
  initials: 'MK',
  role: 'Frontend Engineer',
  location: 'Islamabad, Pakistan',
  email: 'muqeetkhan010@gmail.com',
  phone: '+92 333 5248912',
  github: 'https://github.com/muqeetkhann',
  linkedin: 'https://linkedin.com/in/muqeet-khan',
  portfolio: '#',
  bio: 'I build fast, scalable, and visually compelling web experiences. 2 years delivering production frontends — from real-time crypto dashboards and SaaS platforms to e-commerce marketplaces and Web3 DeFi apps.',
}

export const EXPERIENCE = [
  {
    role: 'Frontend Engineer',
    company: 'Fexen Smart Solutions',
    period: '09/2024 – Present',
    location: 'Islamabad, Pakistan',
    accent: '#6EE7B7',
    bullets: [
      'Owned complete frontend architecture on 10+ client projects from initial setup to production deployment.',
      'Built complex, responsive UIs using React 18/19, Next.js App Router, and TypeScript with a focus on performance and reusability.',
      'Engineered advanced features: drag-and-drop page builders, real-time WebSocket dashboards, and role-based access control systems.',
      'Developed and maintained component libraries of 30–80+ components using Radix UI, Tailwind CSS, and shadcn/ui.',
      'Integrated third-party services including Stripe, Firebase, Google OAuth, Brevo, and Web3 wallet providers.',
    ],
  },
  {
    role: 'Frontend Developer Intern',
    company: 'Stack One Technologies',
    period: 'Sep 2024 – 2025',
    location: 'Islamabad, Pakistan',
    accent: '#93C5FD',
    bullets: [
      'Built responsive UIs with React.js, Tailwind CSS, and Bootstrap; optimised performance via lazy loading and code splitting.',
      'Implemented form validation, dynamic rendering, and React Router for SPA experiences.',
      'Practised Git-based version control and feature branching in an agile team environment.',
    ],
  },
]

export const PROJECTS = [
  {
    id: 1,
    title: 'JitSuites',
    type: 'SaaS Platform',
    url: 'https://jitsuites.com',
    urlLabel: 'jitsuites.com',
    cat: 'saas',
    accent: '#6EE7B7',
    num: '01',
    desc: 'Multi-channel marketing automation platform — funnel builder, email/SMS marketing, social media auto-posting, and video marketing from a single dashboard.',
    highlights: [
      'Architected drag-and-drop funnel/landing page builder using @dnd-kit with element tree manipulation, undo/redo history, layer management, and JSON/HTML export.',
      'Built visual email builder with React Email Editor, merge tag validation, and multi-platform scheduling via React Big Calendar.',
      'Developed 30+ reusable UI components; data tables with server-side pagination, sorting, filtering, and URL state persistence via TanStack Table.',
    ],
    tags: ['React 19', 'TanStack Router', 'TanStack Query', 'Zustand', '@dnd-kit', 'Radix UI', 'Brevo API'],
  },
  {
    id: 2,
    title: 'Kompra',
    type: 'E-Commerce Marketplace',
    url: 'https://dropex-marketplace.pages.dev',
    urlLabel: 'dropex-marketplace.pages.dev',
    cat: 'ecom',
    accent: '#93C5FD',
    num: '02',
    desc: 'Full-featured multi-sided marketplace with a public storefront, seller dashboard, and role-based admin panel for order managers, staff, and procurement managers.',
    highlights: [
      'Architected three distinct interfaces — public storefront, seller dashboard with granular RBAC (order/staff/procurement managers), and admin panel.',
      'Implemented dynamic category-based recommendations via recursive tree traversal and multi-step checkout with optimistic UI updates.',
      'Integrated OTP authentication flow, i18next English/Spanish localization, and persistent cart state via Zustand.',
    ],
    tags: ['React 18', 'TanStack Router', 'TanStack Query', 'Zustand', 'TypeScript', 'Radix UI', 'i18next'],
  },
  {
    id: 3,
    title: 'Dropi Clone',
    type: 'B2B SaaS / Logistics',
    url: 'https://dropi-clone.pages.dev',
    urlLabel: 'dropi-clone.pages.dev',
    cat: 'saas',
    accent: '#FDE68A',
    num: '03',
    desc: 'B2B dropshipping and logistics SaaS for Latin American sellers — manages products, orders, warehouses, and earnings with role-based access control.',
    highlights: [
      'Implemented RBAC with three user types using TanStack Router beforeLoad hooks, dynamic sidebar filtering, and token-based redirects.',
      'Built centralized API client with JWT injection, automatic refresh token storage, and content-type negotiation for JSON/FormData/CSV.',
      'Delivered 80+ reusable components, 15+ API service modules, Vitest unit tests, and full TypeScript coverage.',
    ],
    tags: ['React 18', 'TanStack Table', 'Recharts', 'Zod', 'React Hook Form', 'i18next', 'Vitest'],
  },
  {
    id: 4,
    title: 'Extsy',
    type: 'Crypto Trading Platform',
    url: 'https://extsy.com',
    urlLabel: 'extsy.com',
    cat: 'web3',
    accent: '#C4B5FD',
    num: '04',
    desc: 'Full-featured crypto trading platform with P2P trading, staking, virtual cards, and Web3 wallet integrations. Built as part of a 10–15 person team.',
    highlights: [
      'Integrated TronWeb and Wagmi for Web3 wallet connections; Stripe payments and Firebase authentication.',
      'Built complex modal systems (staking, KYC, payment flows), real-time data tables, and role-based route protection.',
      'Implemented dark/light theme with persistent state; Framer Motion and Lottie animations throughout.',
    ],
    tags: ['Next.js 14', 'Redux Toolkit', 'Chakra UI', 'Wagmi', 'TronWeb', 'Framer Motion', 'Stripe'],
  },
  {
    id: 5,
    title: 'ASAP Pay',
    type: 'Fintech SaaS Dashboard',
    url: 'https://asap-stg.pages.dev',
    urlLabel: 'asap-stg.pages.dev',
    cat: 'web3',
    accent: '#FCA5A5',
    num: '05',
    desc: 'Fintech SaaS enabling crypto/fiat wallet management, P2P trading, currency swapping, virtual card issuance, bill payments, and AI-powered financial assistance.',
    highlights: [
      'Built 40+ routes with responsive layouts, Framer Motion animations, and Ant Design components.',
      'Developed P2P trading interfaces with trade modals, payment status indicators, countdown timers, and virtual card management.',
      'Implemented complete auth UI — login, signup, OTP verification, and 2FA setup using React Hook Form.',
    ],
    tags: ['React 18', 'TypeScript', 'Ant Design', 'TanStack Query', 'Framer Motion', 'i18n'],
  },
  {
    id: 6,
    title: 'Ethoro',
    type: 'Web3 / DeFi',
    url: 'https://dev.ethoro.io',
    urlLabel: 'dev.ethoro.io',
    cat: 'web3',
    accent: '#6EE7B7',
    num: '06',
    desc: 'Crypto staking platform for ERC-20 tokens with Web3 wallet integration and admin dashboard for managing tokens, subscriptions, and withdrawals.',
    highlights: [
      'Engineered Web3 deposit flow with ERC20 approval, smart contract interaction, token decimals conversion, and multi-step wallet confirmations.',
      'Architected JWT-based protected routes with TanStack Router beforeLoad hooks, automatic token refresh, and role-based redirects.',
      'Built admin layer with Chart.js analytics, CSV data exports, and referral/withdrawal management.',
    ],
    tags: ['React 19', 'Wagmi / viem', 'Reown AppKit', 'TanStack Query', 'Tailwind CSS v4', 'Sepolia'],
  },
  {
    id: 7,
    title: 'Katana Healthcare',
    type: 'Marketing Website',
    url: 'https://katana-healthcare.com',
    urlLabel: 'katana-healthcare.com',
    cat: 'site',
    accent: '#93C5FD',
    num: '07',
    desc: 'SaaS marketing site for a clinical decision support platform targeting healthcare professionals with BNF-based prescribing tools.',
    highlights: [
      'Engineered synchronized dual-vertical Swiper carousel with real-time center image updates and bidirectional slide sync.',
      'Implemented scroll-aware sticky header with directional visibility detection (hide on scroll-down, reveal on scroll-up).',
      'Deployed to Vercel with HubSpot forms, Google Analytics, and Microsoft Clarity integration.',
    ],
    tags: ['Next.js 16', 'React 19', 'Tailwind CSS 4', 'Swiper 12', 'HubSpot'],
  },
  {
    id: 8,
    title: 'ZawayaDAO',
    type: 'Web3 Marketing Site',
    url: 'https://zawayadao.com',
    urlLabel: 'zawayadao.com',
    cat: 'site web3',
    accent: '#C4B5FD',
    num: '08',
    desc: 'White-label SaaS for real estate tokenization with DAO-ready RWA infrastructure and a custom WebGL interactive background.',
    highlights: [
      'Engineered PixelBlast component with custom GLSL fragment shaders — FBM noise, liquid ripple effects, and pointer tracking.',
      'Implemented IntersectionObserver scroll animations, JSON-LD structured data, and SEO-optimized metadata.',
    ],
    tags: ['Next.js 16', 'Three.js', 'GLSL Shaders', 'TypeScript', 'Tailwind CSS 4'],
  },
  {
    id: 9,
    title: 'Travaleo',
    type: 'Real Estate Platform',
    url: 'https://travaleo.com',
    urlLabel: 'travaleo.com',
    cat: 'site',
    accent: '#FDE68A',
    num: '09',
    desc: 'Tokenized real estate investment platform enabling fractional ownership of luxury properties for high-net-worth investors.',
    highlights: [
      'Integrated dual CMS APIs (Strapi + custom REST) with unified TypeScript interfaces and React Query caching.',
      'Built TokenCard components with Swiper galleries, dynamic ROI calculations, and funding progress bars.',
      'Full SEO stack: Schema.org structured data, Open Graph tags, Google Analytics, and server-side rendering.',
    ],
    tags: ['Next.js 15', 'Strapi CMS', 'TanStack Query', 'Radix UI', 'shadcn/ui', 'Swiper'],
  },
  {
    id: 10,
    title: 'Singularity',
    type: 'Web3 / DeFi',
    url: 'https://singularity-web-app-lime.vercel.app',
    urlLabel: 'singularity-web-app-lime.vercel.app',
    cat: 'web3',
    accent: '#6EE7B7',
    num: '10',
    desc: 'DeFi yield farming platform with Ethereum wallet connectivity, smart contract interaction, and real-time on-chain metrics dashboard.',
    highlights: [
      'Implemented Ethereum wallet connectivity using Reown AppKit with wagmi/viem, supporting mainnet and Sepolia with automatic chain switching.',
      'Built async data hooks using viem contract read functions integrated with React Query for real-time on-chain state.',
      'Created protected routes validating wallet connection status with multi-chain header support.',
    ],
    tags: ['Next.js 16', 'Wagmi / viem', 'Reown AppKit', 'TanStack Query', 'Tailwind CSS 4', 'DeFi'],
  },
  {
    id: 11,
    title: 'Blockyfy',
    type: 'Agency Website',
    url: '',
    urlLabel: '',
    cat: 'site',
    accent: '#6EE7B7',
    num: '11',
    desc: 'Agency site with custom country code selector (50+ countries), Cal.com scheduling, and WhatsApp chat.',
    highlights: [],
    tags: ['React', 'Tailwind', 'Cal.com'],
  },
  {
    id: 12,
    title: 'NextSense',
    type: 'Tech Website',
    url: '',
    urlLabel: '',
    cat: 'site',
    accent: '#93C5FD',
    num: '12',
    desc: 'Web3/AI tech site with complex multi-level dropdown nav and dynamic dark/light mode per page.',
    highlights: [],
    tags: ['Next.js', 'Tailwind', 'Dark Mode'],
  },
  {
    id: 13,
    title: 'Regen Digital',
    type: 'RWA Tokenization',
    url: '',
    urlLabel: '',
    cat: 'site',
    accent: '#C4B5FD',
    num: '13',
    desc: 'Real estate tokenization site with 8+ pages and reusable component system utilizing class-variance-authority for tight UI scaling.',
    highlights: [],
    tags: ['Next.js', 'CVA', 'Tailwind'],
  },
]

export const SKILLS = [
  { cat: 'Languages', items: ['JavaScript (ES6+)', 'TypeScript', 'HTML5', 'CSS3', 'GLSL'] },
  { cat: 'Frameworks', items: ['React 18/19', 'Next.js (App Router)', 'TanStack Router', 'TanStack Query', 'TanStack Table'] },
  { cat: 'State Mgmt', items: ['Zustand', 'Redux Toolkit', 'Context API', 'React Hook Form', 'Zod'] },
  { cat: 'Styling', items: ['Tailwind CSS 4', 'Radix UI', 'shadcn/ui', 'Framer Motion', 'Chakra UI', 'Ant Design'] },
  { cat: 'Web3', items: ['Wagmi / viem', 'Reown AppKit', 'TronWeb', 'ERC-20', 'Smart Contracts', 'Three.js'] },
  { cat: 'Integrations', items: ['REST APIs', 'WebSockets', 'Stripe', 'Firebase', 'Google OAuth', 'Brevo', 'HubSpot'] },
  { cat: 'Tooling', items: ['Git / GitHub', 'Vercel', 'Vite', 'Vitest', 'ESLint / Prettier', 'i18next'] },
]

export const FILTERS = [
  { label: 'All', value: 'all' },
  { label: 'SaaS / Platforms', value: 'saas' },
  { label: 'Web3 / Crypto', value: 'web3' },
  { label: 'E-Commerce', value: 'ecom' },
  { label: 'Marketing Sites', value: 'site' },
]
